name: test build musllinux
on:
  push
jobs:
  aarch64_wheels:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - {version: '3.10', abi: 'cp310'}
          - {version: '3.11', abi: 'cp311'}
          - {version: '3.12', abi: 'cp312'}
    name: Python ${{ matrix.python.version }} with ABI ${{ matrix.python.abi }} for musllinux
    env:
      WHEELNAME: rbcl-${{ github.ref_name }}-${{ matrix.python.abi }}-

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Python.
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python.version }}
          architecture: x64
      - name: Download libsodium source tree archive.
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
          mv libsodium-1.0.18.tar.gz src/rbcl/libsodium.tar.gz
      - name: Install Python dependencies for build process.
        run: |
          pip install .[build]
      - name: Build wheel file.
        run: |
          mkdir tmpwheelhouse
          LIBSODIUM_MAKE_ARGS="-j$(nproc)" python -m build --wheel
          mv dist/rbcl*.whl tmpwheelhouse
          mkdir wheelhouse
          mv tmpwheelhouse/rbcl*.whl wheelhouse/
          cp build/lib*/rbcl/_sodium.py src/rbcl/_sodium.py

      - name: Test wheel installation.
        run: |
          pip install -f wheelhouse --no-index --force-reinstall --no-dependencies rbcl

      - name: Upload wheel file.
        run: |
          mkdir rbcl-wheelhouse
          mv wheelhouse/rbcl*.whl rbcl-wheelhouse/${{ env.WHEELNAME }}.whl
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.WHEELNAME }}
          path: rbcl-wheelhouse/