name: test build musllinux
on:
  push
jobs:
  aarch64_wheels:
    name: Build wheels for aarch64 linux
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Install Python.
        uses: actions/setup-python@v4
      - name: Download libsodium source tree archive.
        run: |
          wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.18.tar.gz
          mv libsodium-1.0.18.tar.gz src/rbcl/libsodium.tar.gz
      - name: Install Python dependencies for build process.
        run: |
          pip install .[build]

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: dist-wheels
          path: dist/*.whl